### ISSUE TITLE
feature przycisk do centrowania mapy

### ISSUE THREAD

**Issue by heisenshark** [Nawigacja-SGGW/mobileapp#23]
tak jak na figmie, jest taki śmieszny przycisk w prawym dolnym, dodać go do mapy

**Comment by G4ND4LFpl** [comment]
Ktoś komu pracuje na dotykowym mógłby sprawdzić, czy wszystko ok, bo ja na emulatorze nie mam tej opcji?
compass-center-button branch

**Comment by heisenshark** [comment]
jak chcesz obracać mape na emulatorze to przytrzymujesz ctrl i obracasz dwie kropki które ci wyskakują @G4ND4LFpl
